### ISSUE TITLE
Project Meeting Minutes

### ISSUE THREAD

**Issue by ardentpark** [ardentpark/CPL-20162-Team5#11]
정기 LAB Meeting 일정 : 격주(1,3주) 월요일 1시 30분~2시(화2~3, 목1~2시30분)

**Comment by ardentpark** [comment]
# 1st Team Meeting
### 회의 일시 : 2016-09-02 PM 20:00
### 회의 장소 : IT 4호관 C Lounge
##### 참여인원 : 6명
_ _ _  

## 회의 내용
* 팀 결성  
* 팀원 소개  
* 팀원 정보 공유

## 회의 결과
* 어렵다, 탐구 필요
* 시간표 대조를 통해 적절한 회의시간을 찾아보자

## 회의 계획
* 연구실 연락
* 시간표 공유   

- - -

**Comment by ardentpark** [comment]
# 1st Lab Meeting & 2nd Team Meeting Meeting 
### 회의 일시 : 2016-09-05 PM 01:30
### 회의 장소 : IT 3호관 208호
##### 참여인원 : 5명 (__불참 : 배봉현__)  
_ _ _  

## 회의 내용
* 연구실, 팀 상호 소개
* 일정 조율
* 과제 소개
 - HAS
 - AIHAS
 - Dash.js
* 프로젝트 주제 선정

## 회의 결과
* 격주 회의  
 - 매월 1, 3주 월요일 1시 30분~2시 예정
 - 화요일 2시~3시, 목요일 1시 30분~2시 후보군
 - 상황에 따라 변동 가능 
* 상시 팀 회의
 - 팀원 6명의 일정 조율 난항으로 상황에 따른 회의 상시 추진 결정
 - 총원 가능 시간 : 목,금 9시 ~ 10시 30분
![image](https://cloud.githubusercontent.com/assets/14334434/18809557/75575cf8-82b9-11e6-8f2c-6e5fe60438fa.png)  
* 인공지능 or 적응형 스트리밍
 - 인공지능이나 적응형 스트리밍 둘 중 하나에 중점을 두어서 결과를 이끌어내라  
* 과제 기반 자유주제
 - 산학연계, 연구실 지정 프로젝트가 아닌 학생주도 프로젝트
 - 연구실은 자문 역할
* 프로젝트 아이디어  
프로젝트 주제 후보 -> #2 
 - Cctv영상 패턴이나 관련 데이터들을 분석하여 가변적인 품질의 cctv 스트리밍을 제공, 효율을 높인다
고속도로cctv를 gps위치 기반으로 가까운 cctv를 선정하여 해당 비디오를 스트리밍한다(고속도로 교통상황 메세징)
 - 평소에 자주 찾는 고속도로. 길. 패턴을 분석해서 즐겨찾기 리스트를 제공하고. 기본적으로는 GPS기반? 사용자가 원하는 영상을 즉시 반강제 재생어린이집 보육원의 cctv가 비정상적인  행동패턴을 인지하여 알림(어린이집 보육원 폭력사고 메세징)
 - 놀이터 cctv가 화면 내 인물 수를 인지(공공시설, 실종 메세징), 테러 예방
 - 카페 등에서 손님의 핸드폰 음악 분석하여 음악선곡(오디오 스트리밍)
 - 미디어아트(날씨나, 상황에 맞는 영상을 송출)
 - VR 적응형 비디오스트리밍

## 회의 계획
* 9월 7일 서류제출
* 9월 4째 주 랩 미팅  
* 프로젝트 주제 선정
* 과제 기술 연구   

- - -  
> 스트리밍, 인공지능 관련 오픈소스
> - mpeg-dash, apache kafka, apache spark, opencv, 텐서플로우, 오드로이드

**Comment by ardentpark** [comment]
### 회의 일시 : 2016-09-09 PM 20:00
### 회의 장소 : 공대 9호관 417호
##### 참여인원 : 6명
_ _ _  

## 회의 내용
* 프로젝트 주제 선정  
* 팀 조직 역할 분담
* 시스템 스펙 논의
* 예산 논의

## 회의 결과
* 패턴(특징)인식, 분석 기반 적응형 CCTV 스트리밍(PRACASH)
* 프로젝트 운영 조직
 - Leader 박순렬
 - Researcher 류호민
 - Liaison 곽준창
 - Bookkeeper 여민규
 - Librarian 정석훈
 - Inspector 배봉현
* 스펙 한계
 - 라즈베리파이로는 한계가 있다, 성능이 떨어지며 지연이 크다
 - 오드로이드의 성능은 좋지만 불확실하다.
 - Intel x86 서버를 갖추는 방안으로 추진하자
* 서버 견적
 - intel x86 서버 견적을 내어 다른 부품들과 함께 예산 100만원에 맞춰 견적을 내자
 - 구매는 사업단 구매보다 학생 구매를 지향한다

## 회의 계획
* 견적 논의, 예산 작성
* 시스템 스펙, 구조 논의
* 세부 계획 논의
  
- - -  
참고자료 #10

**Comment by ardentpark** [comment]
### 회의 일시 : 2016-09-19 PM 20:00
### 회의 장소 : 공대 9호관 415호
##### 참여인원 : 4명 (__불참 : 정석훈, 곽준창__)
_ _ _  

## 회의 내용
* 견적, 예산 작성
* 시스템 스펙, 구조
* 세부 계획
* 추진 일정
* 개발 역할 분담
* 계획서 작성

## 회의 결과
* Plan A, Plan B Asset #5 
 - Plan A : Intel x86 기반 스펙
 - Plan B : odroid 기반 스펙
 - LINC 사업단에 Plan A,B 에 대해 문의 후 결과에 따라 결정
* Apache Spark
 - Apache kafka, Apache spark 의 서버 구성을 하자
 - 영상처리는 텐서플로우 등의 기계학습 인공지능을 이용하지 말고 OpenCV를 이용하자  
* 테스트 개발
 - 테스트 서버에서 얼굴 인식은 성공
 - 클라이언트 사이드에서의 dash.js 개발이 필요하다
* 추진 일정, 역할 분담
 - 세부 시스템 구조, 개발 도메인이 나오는 것을 바탕으로 조율, 배치 예정
* 계획서(과제, 수행) 작성 분담 #4 


## 회의 계획
* 견적, 품의서 논의, 예산 추가 항목 고민 
* 9월 22일 목요일, 팀 회의 및 LINC 사업단 의뢰 예정
* 일정, 개발 역할 결정
  
- - -  
![kakaotalk_20160919_204206071](https://cloud.githubusercontent.com/assets/14334434/18809759/7563bc04-82bf-11e6-9eb5-15ac7720ba6d.jpg)

**Comment by ardentpark** [comment]
### 회의 일시 : 2016-09-22 AM 10:30
### 회의 장소 : GP Cafe
##### 참여인원 : 3명 (__불참 : 곽준창, 배봉현, 정석훈__)  
_ _ _  

## 회의 내용
 * 견적, 품의서 논의, 예산 추가 항목 고민
 * 시스템 구조 논의 
 * LINC 사업단 의뢰 
 * 일정, 개발 역할 결정

## 회의 결과
* 견적 수정
 - intel x86에 대한 사업단의 허가가 힘들기 때문에 오드로이드로 하향 조정
 - 필요한의 최소 스펙에 맞추어 예산 작성, 집행  
* PRACASH 시스템 구조
 - 시스템 구상 디자인을 바탕으로 조율, 수정하여 최종 결정 예정 #8  
* 사유서 제출 고려
 - 사업단 측의 불허에 대해 사유서로 중재
* 일정, 개발 역할
 - 시스템 구조에 맞춰 개발 일정 수립
 - 개발 역할은 팀원 각각의 역량에 맞추어 분담 고려

## 회의 계획
* 9월 22일 오후 2시 랩 미팅  
* 시스템 구조 논의
* 연구실 예산 자문 의뢰 

- - -  
![예산 견적표](https://cloud.githubusercontent.com/assets/14334434/18810034/edfcde28-82c6-11e6-8f55-80fd9c11ad74.png)

**Comment by ardentpark** [comment]
### 회의 일시 : 2016-09-22 PM 01:30
### 회의 장소 : IT 3호관 208호
##### 참여인원 : 5명 (__불참 : 류호민__)  
_ _ _  

## 회의 내용
 * 시스템 구조
 * 예산 자문 
 * 프로젝트 설계

## 회의 결과
* 프로젝트 기획 및 PRACASH 시스템 #9 
 - 스트리밍이 HAS를 거치는 것을 빼는 방향으로 고려
 - 구조도의 OpenCV 등의 위치를 계층에 맞게 수정
 - 아파치 서버 구축 등 중요한 것 부터 먼저 하고 여유가 있으면 추가 서비스 개발 구현 작업 추진
* 시스템 견적
 - 영상 처리 및 스트리밍을 위해서는 고사양의 서버가 필요
 - CPU, GPU 등 요구되는 스펙에 예산을 맞추기는 어렵고 불확실한 점이 있다
 - 사업단에 무리하게 예산 요구하는 것 보다 최소한의 스펙으로 우선 추진하고 상황에 따른 수정 예산 집행 하는 것을 고려
* 논문 및 특허 출원
 - 논문의 경우 투고만 하면 되는 것으로 추정됨
 - 논문 및 특허를 업체에 맡기지 않고 개인이 쓰는 것으로 추진 
 - 프로젝트 일정에서 논문 작성 및 특허 출원 일정을 추가

## 회의 계획
* 10월 6일 점심 또는 저녁시간 랩 미팅  
* 시스템 요구 명세 자문
*  요구 명세, 설계, 특허 등 서류 작성

- - -

**Comment by ardentpark** [comment]
# 6th Team Meeting

**Comment by BaeBongHyeon** [comment]
# 6th Team Meeting
### 회의 일시 : 2016-09-29 PM 07:00
### 회의 장소 : 공대 9호관 과방
##### 참여인원 : 4명 (__불참 : 류호민, 곽준창__)  
_ _ _  

## 회의 내용
 * 물품 수령 확인
 * Requirement analysis 작성
 * Usecase scenario 작성

## 회의 결과
* 물품 수령 확인
 - Odroid를 제외한 다른 물품 수령 확인
* Requirement analysis
 - 대략적인 requirement 작성 완료
 - 관리자와 사용자의 접근정도를 다음 회의 때 정하기로 함
 - dash.js관련된 기능 정보를 functional requirement에 추가할 것
* Usecase scenario
 - 스트리밍 영상보기, 녹화된 영상보기, 레포트 관리 세가지로 scenario작성 완료
## 회의 계획
* 10월 4일 또는 5일 저녁시간 팀 미팅
* 10월 7일에 있을 발표자료 작성
* 10월 6일 점심 또는 저녁시간 랩 미팅

- - -

**Comment by BaeBongHyeon** [comment]
# 7th Team Meeting
### 회의 일시 : 2016-10-05 PM 07:00
### 회의 장소 : 공대 9호관 실습실B
##### 참여인원 : 6명
_ _ _  

## 회의 내용
 * 물품 수령 및 추가구매 물품 확인
 * 발표자료 준비 
 * 서류작성 회의
 
## 회의 결과

* 물품 수령 및 추가구매 물품 확인
 - Odroid 물품 수령 확인
 - 추가적으로 필요한 물품은 작업중 다시 확인하기로 함  


* 발표자료 목차
 - 개요 (프로젝트에 관한 구체적인 설명)
 - Requirement, 적용범위 등 설명
 - 개발 역할분담 소개
 - 기술배경 설명 (Spark, Kafka, Dash.js)
 - 논문, 설계 진행상황 (Github를 통해 보여주기)
 

* 서류작성 회의
 - 논문 작성 (11월 11일까지 투고)
 - SRS(요구명세서) 작성 (10월 7일까지 1차 작성후 10월 9일 마무리)
 - SDD(소프트웨어 기술설계서) 작성(요구명세서 작성 완료후 진행)


## 회의 계획
* 10월 6일 점심시간 랩 미팅
* 10월 7일 SRS 1차 확인 팀 미팅
* 10월 7일에 있을 발표자료 작성


- - -

**Comment by Seok-HunJeong** [comment]
# 8th Team Meeting
### 회의 일시  :2016-10-06 PM 00:10 ~ 01:25
### 회의 장소 : IT 3호관 208호
##### 참여인원 : 4명 (불참자 : 배봉현, 곽준창)
_ _ _  

## 회의 내용
 * 변경사항 보고
 * 10월 7일 발표 내용정리
 * 논문&특허 작성 일정 파악
 * 프로젝트 진행에 관한 자문
 
## 회의 결과

* 논문 검색할 수 있는 사이트 정보
 - DBPIA : 학교 내 PC는 라이센스가 있으므로 무료로 논문검색 가능
 - Google Scholar : 국내,외 논문 검색 가능

* dash.js를 이용하여 실시간 스트리밍이 가능 할 수 있을지에 대한 이슈
 문제점 : dash.js는 서버에 이미 존재하는 비디오 파일을 불러 오는것이기 때문에 라즈베리파이에서 촬영한 영상을 파일로 만들고 다시 그걸 읽어오면 딜레이가 큼.
  - 방안 1. 서버에 비디오를 1초씩 짧게 저장하고 바로 읽어오면 딜레이가 줄어들 수 있음.
  - 방안 2. dash.js코드를 참고하여 실시간 스트리밍이 되도록 직접 만들어 사용.(lab추천)

* Lab 서버 대여 가능여부
 - 서버 대여는 가능. 단 IP할당을 통한 원격사용만 가능. PC를 직접 가지고 오는 것은 불가능.

* 프로젝트 개발 시기에 대한 회의
 - 공식적으로는 10/24 개발 시작이나, 원할한 개발착수를 위해 중간고사 전 제반작업 완료(OS설치 등)
 - 10/24 ~ 11/4(중간발표)까지 기간이 10일 남짓이므로 촉박할것으로 예상. 중간고사가 빨리 끝나는 팀원끼리 미리 개발 시작이 요망됨.

## 회의 계획
* 10월 7일 SRS 1차 확인 팀 미팅
* 11월 4일 중간발표 준비와 논문 작성을 위해 중간고사 이후 2번의 미팅계획(10/28쯤 날짜 미정)


- - -
