### ISSUE TITLE
OpenCV

### ISSUE THREAD

**Issue by ardentpark** [ardentpark/CPL-20162-Team5#12]
# OpenCV 참고 자료

**Comment by ardentpark** [comment]
# Python-OpenCV Face Detection Test

```
from picamera.array import PiRGBArray
from time import sleep
from picamera import PiCamera
import cv2

#import wiringpi2
#wiringpi.wiringPiSetup()

camera = PiCamera()
camera.resolution = (320, 280)
camera.framerate = 10

rawCapture = PiRGBArray(camera, size=(320, 280))
sleep(0.5)

#camera.start_preview()
face_cascade = cv2.CascadeClassifier('/home/rumo/haar.xml')

for frame in camera.capture_continuous(rawCapture, format="bgr", use_video_port=True):
        image = frame.array

        # face detection
        gray = cv2.cvtColor(image,cv2.COLOR_BGR2GRAY)

        faces = face_cascade.detectMultiScale(gray, 1.1, 5)
        for (x,y,w,h) in faces:
                cv2.rectangle(image,(x,y),(x+w,y+h),(255,0,0),2)

        #DISPLAY TO WINDOW
        cv2.imshow("Faces", image)

        rawCapture.truncate(0)

        if key == 27:
                camera.close()
                cv2.destroyAllWindows()
                break

#camera.stop_preview()
```

[참고사이트링크](http://www.knight-of-pi.org/op)

**Comment by ardentpark** [comment]
![image](https://cloud.githubusercontent.com/assets/11865340/18407677/3028840c-7753-11e6-802c-58f289062150.png)

**Comment by Seok-HunJeong** [comment]
![default](https://cloud.githubusercontent.com/assets/20656103/19893889/30a10cce-a08e-11e6-82ac-476c51e62f80.png)

import cv2
import numpy as np

def diffImage(i):
    diff0 = cv2.absdiff(i[0], i[1])
    diff1 = cv2.absdiff(i[1], i[2])
    return cv2.bitwise_and(diff0, diff1)

def getGrayCameraImage(cam):
    img=cam.read()[1]
    gimg=cv2.cvtColor(img, cv2.COLOR_RGB2GRAY)
    return gimg

def updateCameraImage(cam, i):
    i[0] = i[1]
    i[1] = i[2]
    i[2] = getGrayCameraImage(cam)

# setup video capture
if __name__ == "__main__":
    thresh = 32
    cam = cv2.VideoCapture(0)
    i = [None, None, None]
    for n in range(3):
        i[n] = getGrayCameraImage(cam)

    while True:
        diff = diffImage(i)
        ret,thrimg=cv2.threshold(diff, thresh, 1, cv2.THRESH_BINARY)
        count = cv2.countNonZero(thrimg)
        if (count > 20):
            nz = np.nonzero(thrimg)
            cv2.rectangle(diff,(min(nz[1]),min(nz[0])),(max(nz[1]),max(nz[0])),(255,0,0),2)
            cv2.rectangle(i[0],(min(nz[1]),min(nz[0])),(max(nz[1]),max(nz[0])),(0,0,255),2)
            cv2.imwrite('detect.jpg',i[0])

        cv2.imshow('Detecting Motion', diff)

        # process next image
        updateCameraImage(cam, i)

        key = cv2.waitKey(10)
        if key == 27:
            break

움직임 감지하고 움직이는 곳 표시해서 캡처하는 코드
캡처하는 부분 코드를 용도에 맞게 고치면 써먹을 수 있을듯
