### ISSUE TITLE
Requirement Analysis

### ISSUE THREAD

**Issue by Seok-HunJeong** [ardentpark/CPL-20162-Team5#25]

**Comment by Seok-HunJeong** [comment]
[RequirementDefinition(sketchy).docx](https://github.com/ardentpark/CPL-20162-Team5/files/497628/RequirementDefinition.sketchy.docx)

**Comment by Seok-HunJeong** [comment]
[소프트웨어설계 Requirement Definition.docx](https://github.com/ardentpark/CPL-20162-Team5/files/497635/Requirement.Definition.docx)
[Use case description1.docx](https://github.com/ardentpark/CPL-20162-Team5/files/497634/Use.case.description1.docx)


Requirement Definition, Use Case description 예시(양식)입니다. 참고용으로 올립니다

**Comment by BaeBongHyeon** [comment]
[Requirement.pdf](https://github.com/ardentpark/CPL-20162-Team5/files/500494/Requirement.pdf)

**Comment by BaeBongHyeon** [comment]
[Usecase.pdf](https://github.com/ardentpark/CPL-20162-Team5/files/500520/Usecase.pdf)

Use case 시나리오 형식 넣었습니다.

**Comment by Seok-HunJeong** [comment]
[cases(0929).docx](https://github.com/ardentpark/CPL-20162-Team5/files/502234/cases.0929.docx)
0929 회의때 나온 케이스들입니다.(실시간영상보기, 녹화영상보기, 레포트보기)
