### ISSUE TITLE
Project Information

### ISSUE THREAD

**Issue by Rumo-Arf** [ardentpark/CPL-20162-Team5#3]
# 프로젝트 정보
* PRACASH
* AIHAS  

## PRACASH 프로젝트 개요 소개
[About PRACASH.pptx](https://github.com/ardentpark/CPL-20162-Team5/files/502100/About.PRACASH.pptx)

**Comment by Rumo-Arf** [comment]
![image](https://cloud.githubusercontent.com/assets/11865340/18407677/3028840c-7753-11e6-802c-58f289062150.png)

**Comment by ardentpark** [comment]
# PRACASH 프로젝트 개요 소개
[About PRACASH.pptx](https://github.com/ardentpark/CPL-20162-Team5/files/499630/About.PRACASH.pptx)

**Comment by ardentpark** [comment]
## AIHAS 제안서, 계획서 hwp파일
[AIHAS 제안서,계획서.zip](https://github.com/ardentpark/CPL-20162-Team5/files/499635/AIHAS.zip)
